//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once
#include "mui/mui.h"
#include "mui/controls.h"
#include <mui/ds_window.h>

class DewesoftBridge;

class BaseSetupWindow : public Dewesoft::MUI::DSWindow
{
public:

protected:
    DewesoftBridge& bridge;

    Dewesoft::MUI::CaptionPanel generalSettingsPanel;
    Dewesoft::MUI::Label triggerChanLabel;
    Dewesoft::MUI::ComboBox triggerChanCBox;
    Dewesoft::MUI::Label triggerLevelLabel;
    Dewesoft::MUI::TextBox triggerLevelTextBox;
    Dewesoft::MUI::Label edgeTypeLabel;
    Dewesoft::MUI::ComboBox edgeTypeCBox;
    Dewesoft::MUI::Label templateFileLabel;
    Dewesoft::MUI::TextBox templateFileTextBox;
    Dewesoft::MUI::Button templateBtn;
    Dewesoft::MUI::Label reportDirLabel;
    Dewesoft::MUI::TextBox reportDirTextBox;
    Dewesoft::MUI::Button reportDirBtn;
    Dewesoft::MUI::Label reportNameLabel;
    Dewesoft::MUI::TextBox reportNameTextBox;
    Dewesoft::MUI::CaptionPanel optionsListPanel;
    Dewesoft::MUI::StackPanel optionsListStackPanel;
    Dewesoft::MUI::CaptionPanel dsGridPanel;
    Dewesoft::MUI::DSDrawGrid selectedChannelsGrid;
    Dewesoft::MUI::Button addChannelBtn;

    BaseSetupWindow(Dewesoft::MUI::WindowPtr& ui, DewesoftBridge& bridge, std::string pathToXmlFile) : DSWindow (ui, pathToXmlFile), bridge(bridge)
    {
        // connect class to UI controls
        generalSettingsPanel = Dewesoft::MUI::CaptionPanel::Connect(ui, "generalSettingsPanel");
        triggerChanLabel = Dewesoft::MUI::Label::Connect(ui, "triggerChanLabel");
        triggerChanCBox = Dewesoft::MUI::ComboBox::Connect(ui, "triggerChanCBox");
        triggerLevelLabel = Dewesoft::MUI::Label::Connect(ui, "triggerLevelLabel");
        triggerLevelTextBox = Dewesoft::MUI::TextBox::Connect(ui, "triggerLevelTextBox");
        edgeTypeLabel = Dewesoft::MUI::Label::Connect(ui, "edgeTypeLabel");
        edgeTypeCBox = Dewesoft::MUI::ComboBox::Connect(ui, "edgeTypeCBox");
        templateFileLabel = Dewesoft::MUI::Label::Connect(ui, "templateFileLabel");
        templateFileTextBox = Dewesoft::MUI::TextBox::Connect(ui, "templateFileTextBox");
        templateBtn = Dewesoft::MUI::Button::Connect(ui, "templateBtn");
        reportDirLabel = Dewesoft::MUI::Label::Connect(ui, "reportDirLabel");
        reportDirTextBox = Dewesoft::MUI::TextBox::Connect(ui, "reportDirTextBox");
        reportDirBtn = Dewesoft::MUI::Button::Connect(ui, "reportDirBtn");
        reportNameLabel = Dewesoft::MUI::Label::Connect(ui, "reportNameLabel");
        reportNameTextBox = Dewesoft::MUI::TextBox::Connect(ui, "reportNameTextBox");
        optionsListPanel = Dewesoft::MUI::CaptionPanel::Connect(ui, "optionsListPanel");
        optionsListStackPanel = Dewesoft::MUI::StackPanel::Connect(ui, "optionsListStackPanel");
        dsGridPanel = Dewesoft::MUI::CaptionPanel::Connect(ui, "dsGridPanel");
        selectedChannelsGrid = Dewesoft::MUI::DSDrawGrid::Connect(ui, "selectedChannelsGrid");
        addChannelBtn = Dewesoft::MUI::Button::Connect(ui, "addChannelBtn");
    }
};
